In [1]:
from google.colab import files
uploaded = files.upload()

Saving pes2021-all-players.csv to pes2021-all-players.csv

In [2]:
# ====================================
# LOAD DATA
# ====================================
import pandas as pd

df = pd.read_csv('pes2021-all-players.csv')

print(df.head())
print(df.columns)

             name shirt_number          team_name                  league  \
0        L. MESSI           10       FC BARCELONA          Spanish League
1      C. RONALDO            7           JUVENTUS             Serie A TIM
2  R. LEWANDOWSKI            9  FC BAYERN MÜNCHEN  Other European Leagues
3          NEYMAR           10                PSG       Ligue 1 Uber Eats
4    K. DE BRUYNE           17       MANCHESTER B          English League

  nationality         region  height  weight  age        foot  ...  \
0   ARGENTINA  South America     170      72   33   Left foot  ...
1    PORTUGAL         Europe     187      83   35  Right foot  ...
2      POLAND         Europe     185      79   32  Right foot  ...
3      BRAZIL  South America     175      68   28  Right foot  ...
4     BELGIUM         Europe     181      68   29  Right foot  ...

  skill_super_sub com_playing_style_trickster  com_playing_style_mazing_run  \
0               0                           1                             1
1               0                           1                             1
2               0                           0                             0
3               0                           1                             1
4               0                           0                             1

   com_playing_style_speeding_bullet  com_playing_style_incisive_run  \
0                                  1                               1
1                                  1                               1
2                                  0                               1
3                                  1                               1
4                                  0                               0

   com_playing_style_early_cross  com_playing_style_long_ball_expert  \
0                              1                                   0
1                              0                                   0
2                              0                                   0
3                              0                                   0
4                              1                                   1

   com_playing_style_long_ranger  ball_color  rating_stars
0                              0       black             5
1                              1       black             5
2                              0       black             5
3                              0       black             5
4                              1       black             5

[5 rows x 120 columns]
Index(['name', 'shirt_number', 'team_name', 'league', 'nationality', 'region',
       'height', 'weight', 'age', 'foot',
       ...
       'skill_super_sub', 'com_playing_style_trickster',
       'com_playing_style_mazing_run', 'com_playing_style_speeding_bullet',
       'com_playing_style_incisive_run', 'com_playing_style_early_cross',
       'com_playing_style_long_ball_expert', 'com_playing_style_long_ranger',
       'ball_color', 'rating_stars'],
      dtype='object', length=120)

In [95]:
# ====================================
# MEMILIH FITUR
# ====================================
import numpy as np

# Kolom yang bukan atribut pemain
exclude_columns = [
    'name',
    'shirt_number',
    'team_name',
    'league',
    'nationality',
    'region',
    'age',
    'foot',
    'condition',
    'injury_resistance',
    'form',
    'com_playing_style_trickster',
    'com_playing_style_mazing_run',
    'com_playing_style_speeding_bullet',
    'com_playing_style_incisive_run',
    'com_playing_style_early_cross',
    'com_playing_style_long_ball_expert',
    'com_playing_style_long_ranger',
    'rating_as_GK',
    'rating_as_CB',
    'rating_as_LB',
    'rating_as_RB',
    'rating_as_DMF',
    'rating_as_CMF',
    'rating_as_LMF',
    'rating_as_RMF',
    'rating_as_AMF',
    'rating_as_LWF',
    'rating_as_RWF',
    'rating_as_SS',
    'rating_as_CF',
    'ball_color',
    'skill_cross_over_turn', 'skill_early_cross', 'skill_first_time_shot', 'skill_incisive_run', 'skill_one_touch_pass', 'skill_chip_shot_control', 'skill_heel_trick', 'skill_man_marking', 'skill_interception', 'skill_gk_penalty_saver', 'skill_penalty_specialist', 'skill_step_on_skill_control', 'skill_rising_shots', 'skill_marseille_turn', 'skill_gk_high_punt', 'skill_heading', 'skill_dipping_shot', 'skill_outside_curler', 'skill_captaincy', 'skill_gamesmanship', 'skill_gk_low_punt', 'skill_low_lofted_pass', 'skill_through_passing', 'skill_fighting_spirit', 'skill_flip_flap', 'skill_weighted_pass', 'skill_pinpoint_crossing', 'skill_sombrero', 'skill_acrobatic_clear', 'skill_cut_behind_turn', 'skill_long_range_drive', 'skill_scotch_move', 'skill_acrobatic_finishing', 'skill_double_touch', 'skill_gk_long_throw', 'skill_long_throw', 'skill_scissors_feint', 'skill_long_range_shooting', 'skill_track_back', 'skill_rabona', 'skill_knuckle_shot', 'skill_no_look_pass', 'skill_super_sub',
    'LWF', 'SS', 'CF', 'RWF', 'LMF', 'DMF', 'CMF', 'AMF', 'RMF', 'LB', 'CB', 'RB',
    'gk_awareness', 'gk_catching', 'gk_clearing', 'gk_reflexes', 'gk_reach'

]

feature_columns = [
    col for col in df.columns
    if col not in exclude_columns
    and np.issubdtype(df[col].dtype, np.number)
]

print(feature_columns)

['height', 'weight', 'offensive_awareness', 'ball_control', 'dribbling', 'tight_possession', 'low_pass', 'lofted_pass', 'finishing', 'heading', 'place_kicking', 'curl', 'speed', 'acceleration', 'kicking_power', 'jump', 'physical_contact', 'balance', 'stamina', 'defensive_awareness', 'ball_winning', 'aggression', 'weak_foot_usage', 'weak_foot_accuracy', 'overall_rating', 'rating_stars']

In [96]:
# ====================================
# NORMALISASI
# ====================================
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(df[feature_columns])

In [59]:
print(df.isna().sum())

# print(df[feature_columns].isna().sum())

name                                  0
shirt_number                          0
team_name                             0
league                                0
nationality                           0
                                     ..
com_playing_style_early_cross         0
com_playing_style_long_ball_expert    0
com_playing_style_long_ranger         0
ball_color                            0
rating_stars                          0
Length: 120, dtype: int64

In [60]:
nan_cols = df[feature_columns].isna().sum()
print(nan_cols[nan_cols > 0].sort_values(ascending=False))

Series([], dtype: int64)

In [61]:
df[feature_columns] = df[feature_columns].fillna(0)

In [62]:
df.head(10)

,name,shirt_number,team_name,league,nationality,region,height,weight,age,foot,...,skill_super_sub,com_playing_style_trickster,com_playing_style_mazing_run,com_playing_style_speeding_bullet,com_playing_style_incisive_run,com_playing_style_early_cross,com_playing_style_long_ball_expert,com_playing_style_long_ranger,ball_color,rating_stars
0,L. MESSI,10,FC BARCELONA,Spanish League,ARGENTINA,South America,170,72,33,Left foot,...,0,1,1,1,1,1,0,0,black,5
1,C. RONALDO,7,JUVENTUS,Serie A TIM,PORTUGAL,Europe,187,83,35,Right foot,...,0,1,1,1,1,0,0,1,black,5
2,R. LEWANDOWSKI,9,FC BAYERN MÜNCHEN,Other European Leagues,POLAND,Europe,185,79,32,Right foot,...,0,0,0,0,1,0,0,0,black,5
3,NEYMAR,10,PSG,Ligue 1 Uber Eats,BRAZIL,South America,175,68,28,Right foot,...,0,1,1,1,1,0,0,0,black,5
4,K. DE BRUYNE,17,MANCHESTER B,English League,BELGIUM,Europe,181,68,29,Right foot,...,0,0,1,0,0,1,1,1,black,5
5,J. OBLAK,13,MADRID ROSAS RB,Spanish League,SLOVENIA,Europe,188,87,27,Right foot,...,0,0,0,0,0,0,0,0,black,5
6,V. VAN DIJK,4,LIVERPOOL R,English League,NETHERLANDS,Europe,193,92,29,Right foot,...,0,0,0,0,0,0,1,0,black,5
7,K. MBAPPÉ,7,PSG,Ligue 1 Uber Eats,FRANCE,Europe,178,73,22,Right foot,...,0,1,1,1,1,0,0,0,black,5
8,SERGIO RAMOS,4,MADRID CHAMARTIN B,Spanish League,SPAIN,Europe,184,82,34,Right foot,...,0,0,0,0,0,0,1,1,black,5
9,S. AGÜERO,10,MANCHESTER B,English League,ARGENTINA,South America,173,70,32,Right foot,...,0,0,1,1,0,0,0,0,black,5

In [97]:
# ====================================
# KNN MODEL
# ====================================
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(
    n_neighbors=6,
    metric='euclidean'
)

knn.fit(X)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [98]:
# ====================================
# CARI PEMAIN MIRIP
# ====================================
def pemain_mirip(nama_pemain):

    pemain = df[
        df['name'].str.lower() == nama_pemain.lower()
    ]

    if pemain.empty:
        print("Pemain tidak ditemukan")
        return

    idx = pemain.index[0]

    distances, indices = knn.kneighbors(
        X[idx].reshape(1, -1)
    )

    hasil = []

    for i in range(1, len(indices[0])):

        pemain_idx = indices[0][i]

        hasil.append({
            "Nama": df.iloc[pemain_idx]["name"],
            "Kemiripan": round(
                (1/(1+distances[0][i]))*100,
                2
            )
        })

    return pd.DataFrame(hasil)

In [116]:
pemain_mirip("C. Ronaldo")

                  Nama  Kemiripan
0       R. LEWANDOWSKI      19.05
1            M. ICARDI      16.36
2            T. MÜLLER      16.11
3  S. MILINKOVIĆ-SAVIĆ      15.54
4              H. KANE      15.32

In [89]:
def compare_player(p1, p2):
    cols = feature_columns

    # a = df[
    #     df['name'].str.lower() == p1.lower()
    # ]
    # b = df[
    #     df['name'].str.lower() == p2.lower()
    # ]

    a = df[df['name'].str.lower() == p1.lower()][cols]
    b = df[df['name'].str.lower() == p2.lower()][cols]

    result = pd.concat([a,b])

    return result.T

In [117]:
compare_player("C. Ronaldo", "R. LEWANDOWSKI")

                       1    2
height               187  185
weight                83   79
offensive_awareness   91   94
ball_control          90   91
dribbling             89   85
tight_possession      88   82
low_pass              83   73
lofted_pass           82   68
finishing             91   92
heading               93   88
place_kicking         83   81
curl                  83   75
speed                 85   83
acceleration          87   79
kicking_power         92   89
jump                  96   89
physical_contact      87   84
balance               85   82
stamina               86   79
defensive_awareness   50   50
ball_winning          58   51
aggression            76   64
weak_foot_usage        3    3
weak_foot_accuracy     4    3
overall_rating        93   92
rating_stars           5    5